version: '3.9'

services:
  postgres:
    user: root
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - "./_postgres:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - forsen
    restart: unless-stopped

  pgadmin:
    user: root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - "./_pgadmin:/var/lib/pgadmin:rw"

    ports:
      - "5050:80"
    expose:
      - "5050"
    networks:
      - forsen

networks:
  forsen:

volumes:
    _postgres:
    _pgadmin: