version: '3.9'

services:
  app:
    image: golang:1.22.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: go run main.go
    ports:
      - 8080:8080

  prometheus:
    user: root
    image: prom/prometheus:v2.45.3
    ports:
      - 9090:9090
    command:
      - --storage.tsdb.retention.time=90d
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/etc/prometheus/data
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    user: root
    image: grafana/grafana:10.3.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./grafana/things:/etc/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    env_file:
      - .env

  postgres:
    user: root
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - "./_postgres:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./_redis:/data
    restart: unless-stopped
